// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfI20ml5_Cr6n7X0ObWUebPCPYjMQR8Uw',
    appId: '1:22415794046:web:b75d33bf287d52c8051d2f',
    messagingSenderId: '22415794046',
    projectId: 'e-commerce-f6ed0',
    authDomain: 'e-commerce-f6ed0.firebaseapp.com',
    storageBucket: 'e-commerce-f6ed0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEX-rb7AZb8p0Q0E9brgCwZyKcd4qSfc',
    appId: '1:22415794046:android:2fce927755b96c74051d2f',
    messagingSenderId: '22415794046',
    projectId: 'e-commerce-f6ed0',
    storageBucket: 'e-commerce-f6ed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAySQUHLiHbGjd4S-kYaDifSeBJW8quvQ',
    appId: '1:22415794046:ios:e5c1e93590ea22c5051d2f',
    messagingSenderId: '22415794046',
    projectId: 'e-commerce-f6ed0',
    storageBucket: 'e-commerce-f6ed0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAySQUHLiHbGjd4S-kYaDifSeBJW8quvQ',
    appId: '1:22415794046:ios:e5c1e93590ea22c5051d2f',
    messagingSenderId: '22415794046',
    projectId: 'e-commerce-f6ed0',
    storageBucket: 'e-commerce-f6ed0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfI20ml5_Cr6n7X0ObWUebPCPYjMQR8Uw',
    appId: '1:22415794046:web:dc5ad91d5b852e05051d2f',
    messagingSenderId: '22415794046',
    projectId: 'e-commerce-f6ed0',
    authDomain: 'e-commerce-f6ed0.firebaseapp.com',
    storageBucket: 'e-commerce-f6ed0.firebasestorage.app',
  );
}
*/